// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDypHcB1n0qUlvbJ0enL9w3xipB4pXYLzQ',
    appId: '1:382626208693:web:bc346af6af41f87a56d7fc',
    messagingSenderId: '382626208693',
    projectId: 'food-recipe-app-effa3',
    authDomain: 'food-recipe-app-effa3.firebaseapp.com',
    storageBucket: 'food-recipe-app-effa3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKBAZrGo7bsl0hqWY0Bfe5kKJ7qJ0L0_w',
    appId: '1:382626208693:android:ffd37d221cf23a0456d7fc',
    messagingSenderId: '382626208693',
    projectId: 'food-recipe-app-effa3',
    storageBucket: 'food-recipe-app-effa3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAymOOaslghL0snvZ_iBPy1mT5E0mxvvUM',
    appId: '1:382626208693:ios:09e876cd07faa1a156d7fc',
    messagingSenderId: '382626208693',
    projectId: 'food-recipe-app-effa3',
    storageBucket: 'food-recipe-app-effa3.appspot.com',
    iosClientId: '382626208693-e26percoi08f5rsad8330p01vu99sl2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodRecipeFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAymOOaslghL0snvZ_iBPy1mT5E0mxvvUM',
    appId: '1:382626208693:ios:09e876cd07faa1a156d7fc',
    messagingSenderId: '382626208693',
    projectId: 'food-recipe-app-effa3',
    storageBucket: 'food-recipe-app-effa3.appspot.com',
    iosClientId: '382626208693-e26percoi08f5rsad8330p01vu99sl2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodRecipeFinal',
  );
}
